# Generated by Django 3.0.6 on 2020-05-31 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('origin', models.CharField(max_length=200)),
                ('temperament', models.TextField()),
                ('lifespan', models.CharField(max_length=100)),
                ('avg_weight', models.CharField(max_length=100)),
                ('avg_height', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=15)),
                ('description', models.TextField()),
                ('spayed_neutered', models.BooleanField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('uploaded_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='dogs.Breed')),
            ],
            options={
                'ordering': ['breed'],
                'unique_together': {('breed', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('breed_name', models.ManyToManyField(related_name='colors', related_query_name='colors', to='dogs.Breed')),
                ('dog_name', models.ManyToManyField(related_name='colors', related_query_name='colors', to='dogs.Dog')),
            ],
        ),
    ]
