# Generated by Django 3.0.6 on 2020-05-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('origin', models.CharField(max_length=200)),
                ('colors', models.TextField()),
                ('temperament', models.TextField()),
                ('lifespan', models.CharField(max_length=100)),
                ('avg_weight', models.CharField(max_length=100)),
                ('avg_height', models.CharField(max_length=100)),
            ],
        ),
    ]
